--
-- PostgreSQL database dump
--

-- Dumped from database version 14.1
-- Dumped by pg_dump version 15.1

-- Started on 2023-01-12 00:53:37 IST

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 274 (class 1259 OID 26143)
-- Name: teams; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.teams (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    "userId" character varying NOT NULL,
    role character varying NOT NULL,
    wid character varying NOT NULL
);


ALTER TABLE public.teams OWNER TO postgres;

--
-- TOC entry 2968 (class 0 OID 0)
-- Dependencies: 274
-- Name: TABLE teams; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.teams IS 'table for all the team members';


--
-- TOC entry 275 (class 1259 OID 26146)
-- Name: teams_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.teams ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.teams_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 2961 (class 0 OID 26143)
-- Dependencies: 274
-- Data for Name: teams; Type: TABLE DATA; Schema: public; Owner: postgres
--

--
-- TOC entry 2971 (class 0 OID 0)
-- Dependencies: 275
-- Name: teams_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.teams_id_seq', 1, false);


--
-- TOC entry 2813 (class 2606 OID 26156)
-- Name: teams teams_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teams
    ADD CONSTRAINT teams_pkey PRIMARY KEY (id);


--
-- TOC entry 2815 (class 2606 OID 26152)
-- Name: teams teams_userId_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.teams
    ADD CONSTRAINT "teams_userId_key" UNIQUE ("userId");


--
-- TOC entry 2959 (class 0 OID 26143)
-- Dependencies: 274
-- Name: teams; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.teams ENABLE ROW LEVEL SECURITY;

--
-- TOC entry 2969 (class 0 OID 0)
-- Dependencies: 274
-- Name: TABLE teams; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.teams TO anon;
GRANT ALL ON TABLE public.teams TO authenticated;
GRANT ALL ON TABLE public.teams TO service_role;


--
-- TOC entry 2970 (class 0 OID 0)
-- Dependencies: 275
-- Name: SEQUENCE teams_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.teams_id_seq TO anon;
GRANT ALL ON SEQUENCE public.teams_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.teams_id_seq TO service_role;


-- Completed on 2023-01-12 00:53:41 IST

--
-- PostgreSQL database dump complete
--

